// © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
//
// 2019 Cog Systems Pty Ltd.
//
// SPDX-License-Identifier: BSD-3-Clause
// This file is automatically generated.

#include <hyptypes.h>
#include <compiler.h>

#include <events/boot.h>

void
allocator_boot_handle_boot_runtime_first_init(void);

void
trace_boot_init(void);

void
aarch64_handle_boot_runtime_init(void);

void
log_init(void);

void
partition_standard_handle_boot_runtime_first_init(void);

void
prng_simple_handle_boot_runtime_first_init(void);

void
vcpu_handle_boot_runtime_init(void);

void
idle_handle_boot_runtime_first_init(cpu_index_t boot_cpu_index);

void
pgtable_handle_boot_runtime_warm_init(void);

void
thread_standard_handle_boot_runtime_warm_init(thread_t *boot_thread);

void
preempt_handle_boot_cpu_early_init(void);

void
partition_standard_handle_boot_cold_init(void);

void
boot_handle_boot_cold_init(void);

void
rcu_bitmap_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
power_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
pgtable_handle_boot_cold_init(void);

void
hyp_aspace_handle_boot_cold_init(void);

void
memdb_bitmap_handle_boot_cold_init(void);

void
partition_standard_boot_add_private_heap(void);

void
irq_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
arm_smccc_handle_boot_cold_init(void);

void
soc_qemu_uart_init(void);

void
watchdog_queue_handle_boot_cold_init(void);

void
addrspace_handle_boot_cold_init(void);

void
arm_vm_mpam_direct_handle_boot_cold_init(void);

void
debug_handle_boot_cold_init(void);

void
ffa_handle_boot_cold_init(void);

void
globals_handle_boot_cold_init(void);

void
idle_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
platform_timer_lp_handle_boot_cold_init(void);

void
scheduler_fprr_handle_boot_cold_init(void);

void
scheduler_trivial_handle_boot_cold_init(void);

void
smmuv3_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
timer_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
timer_lp_queue_handle_boot_cold_init(void);

void
vet_handle_boot_cold_init(void);

void
partition_standard_boot_create_root_partition(void);

void
cpulocal_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
gicv3_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
arm_vm_timer_handle_boot_cpu_cold_init(void);

void
ete_handle_boot_cpu_cold_init(void);

void
platform_pmu_handle_boot_cpu_cold_init(void);

void
platform_timer_handle_boot_cpu_cold_init(void);

void
soc_qemu_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
timer_lp_queue_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
vcpu_arch_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
vdebug_handle_boot_cpu_cold_init(void);

void
vetm_handle_boot_cpu_cold_init(void);

void
vtrbe_handle_boot_cpu_cold_init(void);

void
power_handle_boot_cpu_warm_init(void);

void
debug_handle_boot_cpu_warm_init(void);

void
rcu_bitmap_activate_current(void);

void
partition_phys_access_cpu_warm_init(void);

void
arch_cortex_a_v80_handle_boot_cpu_warm_init(void);

void
arch_cortex_a_v82_handle_boot_cpu_warm_init(void);

void
arch_cortex_a_v9_handle_boot_cpu_warm_init(void);

void
arch_neoverse_v1_handle_boot_cpu_warm_init(void);

void
arm_vm_timer_handle_boot_cpu_warm_init(void);

void
gicv3_handle_boot_cpu_warm_init(void);

void
platform_pmu_handle_boot_cpu_warm_init(void);

void
platform_timer_handle_boot_cpu_warm_init(void);

void
vcpu_handle_boot_cpu_warm_init(void);

void
vdebug_handle_boot_cpu_warm_init(void);

void
vete_handle_boot_cpu_warm_init(void);

void
vgic_handle_boot_cpu_warm_init(void);

void
partition_standard_handle_boot_hypervisor_start(void);

void
arm_vm_timer_handle_boot_hypervisor_start(void);

void
idle_thread_init(void);

void
platform_pmu_handle_boot_hypervisor_start(void);

void
platform_timer_handle_boot_hypervisor_start(void);

void
platform_timer_lp_handle_boot_hypervisor_start(void);

void
prng_simple_handle_boot_hypervisor_start(void);

void
smmuv3_handle_boot_hypervisor_start(void);

void
vetm_handle_boot_hypervisor_start(void);

void
vgic_handle_boot_hypervisor_start(void);

void
watchdog_handle_boot_hypervisor_start(void);

void
etm_handle_boot_hypervisor_start(void);

void
tests_thread_init(void);

void
rootvm_init(void);

void
preempt_handle_boot_cpu_start(void);

void
power_handle_boot_hypervisor_handover(void);

void
gicv3_handle_boot_hypervisor_handover(void);

void
trigger_boot_runtime_first_init_event(cpu_index_t boot_cpu_index)
{
    allocator_boot_handle_boot_runtime_first_init();
    trace_boot_init();
    aarch64_handle_boot_runtime_init();
    log_init();
    partition_standard_handle_boot_runtime_first_init();
    prng_simple_handle_boot_runtime_first_init();
    vcpu_handle_boot_runtime_init();
    idle_handle_boot_runtime_first_init(boot_cpu_index);
}

void
trigger_boot_runtime_warm_init_event(thread_t *boot_thread)
{
    aarch64_handle_boot_runtime_init();
    pgtable_handle_boot_runtime_warm_init();
    vcpu_handle_boot_runtime_init();
    thread_standard_handle_boot_runtime_warm_init(boot_thread);
}

void
trigger_boot_cpu_early_init_event(void)
{
    preempt_handle_boot_cpu_early_init();
}

// boot_cold_init 事件分发：只在 Boot CPU 冷启动跑一次。
// 调用顺序由各模块 .ev 的 priority 生成（数字越大越早；first 最早，last 最晚）。
void
trigger_boot_cold_init_event(cpu_index_t boot_cpu_index)
{
    // first：激活静态 partition_hyp，记下镜像 VA/PA 映射，把剩余 bootmem 交给 hyp allocator。
    // 后面的模块都假定 partition_get_private() 已可用。
    partition_standard_handle_boot_cold_init();
    // VERBOSE 构建下给引导栈底部填红区，供 idle 时检测栈溢出。
    boot_handle_boot_cold_init();
    // 把 Boot CPU 标成 RCU 活跃，之后的 grace period 才会计入这颗核。
    rcu_bitmap_handle_boot_cold_init(boot_cpu_index);
    // 初始化每核电源投票/状态：Boot CPU 记为 COLD_BOOT 且 vote=1（防止启动中被挂起），其余核 OFF。
    power_handle_boot_cold_init(boot_cpu_index);
    // priority 30：初始化 hypervisor 页表控制块（从 partition_hyp 取页）。
    pgtable_handle_boot_cold_init();
    // priority 20：映射 hyp 镜像的物理访问窗口，并分配 aspace 区域 bitmap。
    hyp_aspace_handle_boot_cold_init();
    // priority 10：memdb 登记 hyp 镜像归 partition_hyp；bootmem 那段改记为 allocator 所有。
    memdb_bitmap_handle_boot_cold_init();
    // priority 9：若私有堆 > 前 2MiB（汇编只映射了那么多），把 aspace 已补映射的剩余 RAM 加进 hyp 堆。
    partition_standard_boot_add_private_heap();
    // 初始化 IRQ 号段树，再广播 irq_init（平台中断控制器）。
    irq_handle_boot_cold_init(boot_cpu_index);
    // 向 EL3 查询 PSCI / SMCCC 版本；没有 PSCI 则 panic。
    arm_smccc_handle_boot_cold_init();
    // QEMU 平台：把 UART 映射进 hyp 地址空间，供控制台输出。
    soc_qemu_uart_init();
    // 初始化看门狗超时队列（锁、链表）。
    watchdog_queue_handle_boot_cold_init();
    // 预留 VMID 0（hypervisor 自己用），guest 地址空间从其余 VMID 分配。
    addrspace_handle_boot_cold_init();
    // 探测 MPAM 硬件是否开启，写入全局 option。
    arm_vm_mpam_direct_handle_boot_cold_init();
    // 读取固件是否禁用 debug，供后续 vdebug 判断。
    debug_handle_boot_cold_init();
    // 与 SPMC/TrustZone 协商 FF-A 版本。
    ffa_handle_boot_cold_init();
    // 初始化全局 option 自旋锁。
    globals_handle_boot_cold_init();
    // 记下 Boot CPU 编号；idle_loop 里只在这颗核上触发一次 idle_start。
    idle_handle_boot_cold_init(boot_cpu_index);
    // 把低功耗 generic timer 的 CNTBase 映射进 hyp 地址空间。
    platform_timer_lp_handle_boot_cold_init();
    // 为每颗存在的 CPU 分配 FPRR 调度器（就绪队列、重调度 timer）。
    scheduler_fprr_handle_boot_cold_init();
    // 平凡调度器：初始化每核 active_thread 锁（与 FPRR 二选一，预览构建里两者都在）。
    scheduler_trivial_handle_boot_cold_init();
    // 映射 SMMU v3 寄存器页，校验硬件 ID 并做控制器初始化。
    smmuv3_handle_boot_cold_init(boot_cpu_index);
    // 初始化所有核的 timer 队列；此刻只有 Boot CPU 标为 online。
    timer_handle_boot_cold_init(boot_cpu_index);
    // 初始化系统级低功耗 timer 队列。
    timer_lp_queue_handle_boot_cold_init();
    // 探测固件是否禁用 CPU trace（VET）。
    vet_handle_boot_cold_init();
    // last：从 hyp 堆分配并激活 root partition，donate 一小块启动堆给它。
    // 其余平台 RAM 要等 boot_hypervisor_start 才登记给 root。
    partition_standard_boot_create_root_partition();
}

void
trigger_boot_cpu_cold_init_event(cpu_index_t cpu)
{
    cpulocal_handle_boot_cpu_cold_init(cpu);
    gicv3_handle_boot_cpu_cold_init(cpu);
    arm_vm_timer_handle_boot_cpu_cold_init();
    ete_handle_boot_cpu_cold_init();
    platform_pmu_handle_boot_cpu_cold_init();
    platform_timer_handle_boot_cpu_cold_init();
    soc_qemu_handle_boot_cpu_cold_init(cpu);
    timer_lp_queue_handle_boot_cpu_cold_init(cpu);
    vcpu_arch_handle_boot_cpu_cold_init(cpu);
    vdebug_handle_boot_cpu_cold_init();
    vetm_handle_boot_cpu_cold_init();
    vtrbe_handle_boot_cpu_cold_init();
}

void
trigger_boot_cpu_warm_init_event(void)
{
    power_handle_boot_cpu_warm_init();
    debug_handle_boot_cpu_warm_init();
    rcu_bitmap_activate_current();
    partition_phys_access_cpu_warm_init();
    arch_cortex_a_v80_handle_boot_cpu_warm_init();
    arch_cortex_a_v82_handle_boot_cpu_warm_init();
    arch_cortex_a_v9_handle_boot_cpu_warm_init();
    arch_neoverse_v1_handle_boot_cpu_warm_init();
    arm_vm_timer_handle_boot_cpu_warm_init();
    gicv3_handle_boot_cpu_warm_init();
    platform_pmu_handle_boot_cpu_warm_init();
    platform_timer_handle_boot_cpu_warm_init();
    vcpu_handle_boot_cpu_warm_init();
    vdebug_handle_boot_cpu_warm_init();
    vete_handle_boot_cpu_warm_init();
    vgic_handle_boot_cpu_warm_init();
}

void
trigger_boot_hypervisor_start_event(void)
{
    partition_standard_handle_boot_hypervisor_start();
    arm_vm_timer_handle_boot_hypervisor_start();
    idle_thread_init();
    platform_pmu_handle_boot_hypervisor_start();
    platform_timer_handle_boot_hypervisor_start();
    platform_timer_lp_handle_boot_hypervisor_start();
    prng_simple_handle_boot_hypervisor_start();
    smmuv3_handle_boot_hypervisor_start();
    vetm_handle_boot_hypervisor_start();
    vgic_handle_boot_hypervisor_start();
    watchdog_handle_boot_hypervisor_start();
    etm_handle_boot_hypervisor_start();
    tests_thread_init();
    rootvm_init();
}

void
trigger_boot_cpu_start_event(void)
{
    preempt_handle_boot_cpu_start();
}

void
trigger_boot_hypervisor_handover_event(void)
{
    power_handle_boot_hypervisor_handover();
    gicv3_handle_boot_hypervisor_handover();
}
