// © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
//
// 2019 Cog Systems Pty Ltd.
//
// SPDX-License-Identifier: BSD-3-Clause
// This file is automatically generated.

#include <hyptypes.h>
#include <compiler.h>

#include <events/boot.h>

void
allocator_boot_handle_boot_runtime_first_init(void);

void
trace_boot_init(void);

void
aarch64_handle_boot_runtime_init(void);

void
log_init(void);

void
partition_standard_handle_boot_runtime_first_init(void);

void
prng_simple_handle_boot_runtime_first_init(void);

void
vcpu_handle_boot_runtime_init(void);

void
idle_handle_boot_runtime_first_init(cpu_index_t boot_cpu_index);

void
pgtable_handle_boot_runtime_warm_init(void);

void
thread_standard_handle_boot_runtime_warm_init(thread_t *boot_thread);

void
preempt_handle_boot_cpu_early_init(void);

void
partition_standard_handle_boot_cold_init(void);

void
boot_handle_boot_cold_init(void);

void
rcu_bitmap_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
power_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
pgtable_handle_boot_cold_init(void);

void
hyp_aspace_handle_boot_cold_init(void);

void
memdb_bitmap_handle_boot_cold_init(void);

void
partition_standard_boot_add_private_heap(void);

void
irq_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
arm_smccc_handle_boot_cold_init(void);

void
soc_qemu_uart_init(void);

void
watchdog_queue_handle_boot_cold_init(void);

void
addrspace_handle_boot_cold_init(void);

void
arm_vm_mpam_direct_handle_boot_cold_init(void);

void
debug_handle_boot_cold_init(void);

void
ffa_handle_boot_cold_init(void);

void
globals_handle_boot_cold_init(void);

void
idle_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
platform_timer_lp_handle_boot_cold_init(void);

void
scheduler_fprr_handle_boot_cold_init(void);

void
scheduler_trivial_handle_boot_cold_init(void);

void
smmuv3_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
timer_handle_boot_cold_init(cpu_index_t boot_cpu_index);

void
timer_lp_queue_handle_boot_cold_init(void);

void
vet_handle_boot_cold_init(void);

void
partition_standard_boot_create_root_partition(void);

void
cpulocal_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
gicv3_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
arm_vm_timer_handle_boot_cpu_cold_init(void);

void
ete_handle_boot_cpu_cold_init(void);

void
platform_pmu_handle_boot_cpu_cold_init(void);

void
platform_timer_handle_boot_cpu_cold_init(void);

void
soc_qemu_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
timer_lp_queue_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
vcpu_arch_handle_boot_cpu_cold_init(cpu_index_t cpu);

void
vdebug_handle_boot_cpu_cold_init(void);

void
vetm_handle_boot_cpu_cold_init(void);

void
vtrbe_handle_boot_cpu_cold_init(void);

void
power_handle_boot_cpu_warm_init(void);

void
debug_handle_boot_cpu_warm_init(void);

void
rcu_bitmap_activate_current(void);

void
partition_phys_access_cpu_warm_init(void);

void
arch_cortex_a_v80_handle_boot_cpu_warm_init(void);

void
arch_cortex_a_v82_handle_boot_cpu_warm_init(void);

void
arch_cortex_a_v9_handle_boot_cpu_warm_init(void);

void
arch_neoverse_v1_handle_boot_cpu_warm_init(void);

void
arm_vm_timer_handle_boot_cpu_warm_init(void);

void
gicv3_handle_boot_cpu_warm_init(void);

void
platform_pmu_handle_boot_cpu_warm_init(void);

void
platform_timer_handle_boot_cpu_warm_init(void);

void
vcpu_handle_boot_cpu_warm_init(void);

void
vdebug_handle_boot_cpu_warm_init(void);

void
vete_handle_boot_cpu_warm_init(void);

void
vgic_handle_boot_cpu_warm_init(void);

void
partition_standard_handle_boot_hypervisor_start(void);

void
arm_vm_timer_handle_boot_hypervisor_start(void);

void
idle_thread_init(void);

void
platform_pmu_handle_boot_hypervisor_start(void);

void
platform_timer_handle_boot_hypervisor_start(void);

void
platform_timer_lp_handle_boot_hypervisor_start(void);

void
prng_simple_handle_boot_hypervisor_start(void);

void
smmuv3_handle_boot_hypervisor_start(void);

void
vetm_handle_boot_hypervisor_start(void);

void
vgic_handle_boot_hypervisor_start(void);

void
watchdog_handle_boot_hypervisor_start(void);

void
etm_handle_boot_hypervisor_start(void);

void
tests_thread_init(void);

void
rootvm_init(void);

void
preempt_handle_boot_cpu_start(void);

void
power_handle_boot_hypervisor_handover(void);

void
gicv3_handle_boot_hypervisor_handover(void);

void
trigger_boot_runtime_first_init_event(cpu_index_t boot_cpu_index)
{
    allocator_boot_handle_boot_runtime_first_init();
    trace_boot_init();
    aarch64_handle_boot_runtime_init();
    log_init();
    partition_standard_handle_boot_runtime_first_init();
    prng_simple_handle_boot_runtime_first_init();
    vcpu_handle_boot_runtime_init();
    idle_handle_boot_runtime_first_init(boot_cpu_index);
}

void
trigger_boot_runtime_warm_init_event(thread_t *boot_thread)
{
    aarch64_handle_boot_runtime_init();
    pgtable_handle_boot_runtime_warm_init();
    vcpu_handle_boot_runtime_init();
    thread_standard_handle_boot_runtime_warm_init(boot_thread);
}

void
trigger_boot_cpu_early_init_event(void)
{
    preempt_handle_boot_cpu_early_init();
}

void
trigger_boot_cold_init_event(cpu_index_t boot_cpu_index)
{
    partition_standard_handle_boot_cold_init();
    boot_handle_boot_cold_init();
    rcu_bitmap_handle_boot_cold_init(boot_cpu_index);
    power_handle_boot_cold_init(boot_cpu_index);
    pgtable_handle_boot_cold_init();
    hyp_aspace_handle_boot_cold_init();
    memdb_bitmap_handle_boot_cold_init();
    partition_standard_boot_add_private_heap();
    irq_handle_boot_cold_init(boot_cpu_index);
    arm_smccc_handle_boot_cold_init();
    soc_qemu_uart_init();
    watchdog_queue_handle_boot_cold_init();
    addrspace_handle_boot_cold_init();
    arm_vm_mpam_direct_handle_boot_cold_init();
    debug_handle_boot_cold_init();
    ffa_handle_boot_cold_init();
    globals_handle_boot_cold_init();
    idle_handle_boot_cold_init(boot_cpu_index);
    platform_timer_lp_handle_boot_cold_init();
    scheduler_fprr_handle_boot_cold_init();
    scheduler_trivial_handle_boot_cold_init();
    smmuv3_handle_boot_cold_init(boot_cpu_index);
    timer_handle_boot_cold_init(boot_cpu_index);
    timer_lp_queue_handle_boot_cold_init();
    vet_handle_boot_cold_init();
    partition_standard_boot_create_root_partition();
}

void
trigger_boot_cpu_cold_init_event(cpu_index_t cpu)
{
    cpulocal_handle_boot_cpu_cold_init(cpu);
    gicv3_handle_boot_cpu_cold_init(cpu);
    arm_vm_timer_handle_boot_cpu_cold_init();
    ete_handle_boot_cpu_cold_init();
    platform_pmu_handle_boot_cpu_cold_init();
    platform_timer_handle_boot_cpu_cold_init();
    soc_qemu_handle_boot_cpu_cold_init(cpu);
    timer_lp_queue_handle_boot_cpu_cold_init(cpu);
    vcpu_arch_handle_boot_cpu_cold_init(cpu);
    vdebug_handle_boot_cpu_cold_init();
    vetm_handle_boot_cpu_cold_init();
    vtrbe_handle_boot_cpu_cold_init();
}

void
trigger_boot_cpu_warm_init_event(void)
{
    power_handle_boot_cpu_warm_init();
    debug_handle_boot_cpu_warm_init();
    rcu_bitmap_activate_current();
    partition_phys_access_cpu_warm_init();
    arch_cortex_a_v80_handle_boot_cpu_warm_init();
    arch_cortex_a_v82_handle_boot_cpu_warm_init();
    arch_cortex_a_v9_handle_boot_cpu_warm_init();
    arch_neoverse_v1_handle_boot_cpu_warm_init();
    arm_vm_timer_handle_boot_cpu_warm_init();
    gicv3_handle_boot_cpu_warm_init();
    platform_pmu_handle_boot_cpu_warm_init();
    platform_timer_handle_boot_cpu_warm_init();
    vcpu_handle_boot_cpu_warm_init();
    vdebug_handle_boot_cpu_warm_init();
    vete_handle_boot_cpu_warm_init();
    vgic_handle_boot_cpu_warm_init();
}

void
trigger_boot_hypervisor_start_event(void)
{
    partition_standard_handle_boot_hypervisor_start();
    arm_vm_timer_handle_boot_hypervisor_start();
    idle_thread_init();
    platform_pmu_handle_boot_hypervisor_start();
    platform_timer_handle_boot_hypervisor_start();
    platform_timer_lp_handle_boot_hypervisor_start();
    prng_simple_handle_boot_hypervisor_start();
    smmuv3_handle_boot_hypervisor_start();
    vetm_handle_boot_hypervisor_start();
    vgic_handle_boot_hypervisor_start();
    watchdog_handle_boot_hypervisor_start();
    etm_handle_boot_hypervisor_start();
    tests_thread_init();
    rootvm_init();
}

void
trigger_boot_cpu_start_event(void)
{
    preempt_handle_boot_cpu_start();
}

void
trigger_boot_hypervisor_handover_event(void)
{
    power_handle_boot_hypervisor_handover();
    gicv3_handle_boot_hypervisor_handover();
}
