// Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
//
// 2019 Cog Systems Pty Ltd.
//
// SPDX-License-Identifier: BSD-3-Clause
// This file is automatically generated.


void
trigger_boot_runtime_first_init_event(cpu_index_t boot_cpu_index);

void
trigger_boot_runtime_warm_init_event(thread_t *boot_thread);

void
trigger_boot_cpu_early_init_event(void);

void
trigger_boot_cold_init_event(cpu_index_t boot_cpu_index);

void
trigger_boot_cpu_cold_init_event(cpu_index_t cpu);

void
trigger_boot_cpu_warm_init_event(void);

void
trigger_boot_hypervisor_start_event(void);

void
trigger_boot_cpu_start_event(void);

void
trigger_boot_hypervisor_handover_event(void);
